#!/bin/bash

MY_DIR="`readlink -f "$0" | sed 's/\/[^\/]*$//'`"
MY_NAME="push.sh"
MY_VERSION="1.0"

ROOT_DIR="!!!ROOT_DIR!!!"
DIR_PREFIX="!!!DIR_PREFIX!!!"
REMOTE_PREFIX="!!!REMOTE_PREFIX!!!"

OPT_SQUASH=" --squash"

# - - - - - - - - - - - - - - - - - - - -
# functions

# - help

echo_help() {
  cat <<EOT
$MY_NAME ($MY_VERSION)
  generated by !!!GEN_APP_NAME!!! (!!!GEN_APP_VERSION!!!)

Usage:
  $MY_NAME [Options] [NAME] [BRANCH]

  NAME (require)
    name for subtree name.

  BRANCH (require)
    branch name for remote.

Options:
  -h
  -?
    display help message

  -s
    disable to \`git push --squash\` option
    default is enabled

EOT
}

# - main features

# = =
# git push
#
# arguments
# $1 ... subtree's name (suffix of dirname and remote name)
push() {
  eval git subtree push $OPT_SQUASH --prefix "$DIR_PREFIX/$1" "$REMOTE_PREFIX$1" "$BRANCH"
}

# - - - - - - - - - - - - - - - - - - - -
# arguments

# - command options

while getopts h?s OPT
do
  case $OPT in
    h|\?) echo_help
          exit 0
          ;;
    s)    OPT_SQUASH="";;
  esac
done

shift $((OPTIND - 1))

# - other arguments

NAME="$1"
BRANCH="$2"

# - - - - - - - - - - - - - - - - - - - -
# guard

# require arguments
# - $NAME
if [ -z "$NAME" ] || [ -z "$BRANCH" ]; then

  echo_help
  exit 1
fi

# - - - - - - - - - - - - - - - - - - - -
# main

cd "$ROOT_DIR"

push "$NAME"

